#!/bin/bash
set -e

# Check that there is a terminal attached
#[[ -t 0 || -p /dev/stdin ]] || exit 0
#[[ "$-" == *i* ]] || exit 0

grepit() { grep -Eo '^[A-Z]{1,}-[0-9]{1,}\b' $*; }
grepid() { grepit -q $1; }

grepid "$1" || {
    branch_name=$(git rev-parse --abbrev-ref HEAD 2>&-)
    grepid <(echo $branch_name) && {
        jid=$(grepit <(echo "$branch_name "))
        #exec < /dev/tty
        #read -p "You are on branch $branch_name, do you want to add \"$jid\" to commit message [Y/n]: " answer
        #grep -qi '^y\?$' <(echo $answer) && \
        sed -i'' "1s/^/$jid /" "$1"
    }
} || exit 0
